head: 
    favicon: "/img/favicon.ico"
    keywords: mathematica,robotics,manipulator,ros,vim,matlab,C/C++,python,git,control theory,lsqyRobot
    backgroundpic : "/img/life.jpg"

Intro:
    name: <img src="/img/logo.png"> 
    slogan: <img src="/img/steveJobsQuote.png">  
    HeadButton: dots 

Nav:
    Home_name: <img src="/img/home.png">  
    is_use_categories : true 
    categories_name: <img src="/img/folder.png"> 
    is_use_about : true
    about_name: <img src="/img/about.png"> 
    is_use_about_friend: true
    is_use_quote: true
    friend_name: <img src="/img/friend.png"> 
    quote_name: <img src="/img/quote.png"> 
    is_use_tags : false
    tags_name : <img src="/img/tag.png">
    pages:

MainFirst:
    name: <img src="/img/lsqyLogo.png">
    description: <img src="/img/myQuote.png">
    pic_url: /img/lsqyRobot.jpg
    goto_ulr: ""

prism: coy

fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# hexo-tag-cloud
tag_cloud:
    textFont: Trebuchet MS, Helvetica
    textColor: '#333'
    textHeight: 25
    outlineColor: '#E2E1D1'
    maxSpeed: 0.5
    pauseOnSelected: false # true 意味着当选中对应 tag 时,停止转动
